[package]
name = "rsync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adler32 = "1.2.0"
md5 = "0.7.0"
log = "0.4.20"
simple_logger = "4.2.0"
hex = { version = "0.4.3", features = [] }